// Generated by prepare-responsive-artwork.py alongside the full integrity manifest.
// Runtime deliberately excludes source paths, hashes, encoder settings and byte budgets.
import manifest from "./responsive-artwork.runtime.json" with { type: "json" };

export type ArtworkKey = keyof typeof manifest;

/** Resolve a retained source key, failing loudly instead of requesting a nonpublic original. */
export function artworkMetadata(source: string) {
  const asset = manifest[source as ArtworkKey];
  if (!asset) throw new Error(`Missing responsive artwork: ${source}`);
  return asset;
}

export interface ArtworkCandidate {
  src: string;
  width: number;
  height: number;
}

/** Width-sorted candidates; ordering is checked against the generator's full manifest. */
export function artworkCandidates(source: string): readonly ArtworkCandidate[] {
  return artworkMetadata(source).candidates;
}

/** Select the first sufficient width, capped at the original's largest delivery copy. */
export function artworkSrc(source: string, width: number): string {
  const candidates = artworkCandidates(source);
  return (candidates.find((candidate) => candidate.width >= width) ?? candidates[candidates.length - 1]).src;
}

/** Filter width descriptors without inventing an upscaled or original-source fallback. */
export function artworkSrcset(source: string, maxWidth = Infinity): string {
  return artworkCandidates(source).filter((candidate) => candidate.width <= maxWidth).map(({ src, width }) => `${src} ${width}w`).join(", ");
}

// CSS backgrounds and HTML preloads/pictures use the same media and density rules.
// Mobile cover crops need more pixels than their narrow visible frame. Never upscale
// beyond the preserved 1672px painting, even on wide or high-density screens.
export const heroBands = [
  { media: "(width < 768px)", widths: [768, 1280] },
  { media: "(768px <= width < 1280px)", widths: [1280, 1672] },
  { media: "(width >= 1280px)", widths: [1672] }
] as const;

/** One selection algorithm feeds picture sources, head preloads and CSS backgrounds. */
export function heroSources(source: string) {
  return heroBands.map(({ media, widths }) => ({
    media,
    src: artworkSrc(source, widths[0]),
    srcset: widths.map((width, index) => `${artworkSrc(source, width)} ${index + 1}x`).join(", "),
    background: `image-set(${widths.map((width, index) => `url("${artworkSrc(source, width)}") ${index + 1}x`).join(", ")})`
  }));
}

/** Bridge the shared density bands into the existing room and Home CSS variable names. */
export function heroStyle(source: string) {
  const sources = heroSources(source);
  return {
    "--hero-art-small": sources[0].background,
    "--hero-art-medium": sources[1].background,
    "--hero-art-wide": sources[2].background,
    "--chapter-painting": "var(--responsive-hero-art)",
    "--haven-scene": "var(--responsive-hero-art)"
  };
}
